### ISSUE TITLE
Release 1.5.2 is defunct (missing archive-path dependency)

### ISSUE THREAD

**Issue by csadorf** [conda-forge/aiida-core-feedstock#46]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Release 1.5.2 is defunct (missing archive-path dependency)

PR https://github.com/aiidateam/aiida-core/pull/4534/ added the `archive-path` dependency to aiida-core (released in version 1.5), but it seems like this recipe was never updated to include it, which means that AiiDA conda-forge release 1.5.2 is defunct.

The problem can be reproduced with:
```
$ conda create -n aiida -c conda-forge aiida-core aiida-core.services
$ conda activate aiida
$ reentry scan
$ verdi import
Traceback (most recent call last):
  File "/home/sadorf/miniconda3/envs/aiida-1.5.2/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "/home/sadorf/miniconda3/envs/aiida-1.5.2/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sadorf/miniconda3/envs/aiida-1.5.2/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sadorf/miniconda3/envs/aiida-1.5.2/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sadorf/miniconda3/envs/aiida-1.5.2/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sadorf/miniconda3/envs/aiida-1.5.2/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sadorf/miniconda3/envs/aiida-1.5.2/lib/python3.7/site-packages/aiida/cmdline/utils/decorators.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/sadorf/miniconda3/envs/aiida-1.5.2/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sadorf/miniconda3/envs/aiida-1.5.2/lib/python3.7/site-packages/aiida/cmdline/commands/cmd_import.py", line 110, in cmd_import
    from aiida.tools.importexport.dbimport.utils import IMPORT_LOGGER
  File "/home/sadorf/miniconda3/envs/aiida-1.5.2/lib/python3.7/site-packages/aiida/tools/importexport/__init__.py", line 18, in <module>
    from .archive import *
  File "/home/sadorf/miniconda3/envs/aiida-1.5.2/lib/python3.7/site-packages/aiida/tools/importexport/archive/__init__.py", line 15, in <module>
    from .migrators import *
  File "/home/sadorf/miniconda3/envs/aiida-1.5.2/lib/python3.7/site-packages/aiida/tools/importexport/archive/migrators.py", line 21, in <module>
    from archive_path import TarPath, ZipPath, read_file_in_tar, read_file_in_zip
ModuleNotFoundError: No module named 'archive_path'
```

The issue can be fixed with `$ conda install -c conda-forge archive-path`.

@ltalirz @chrisjsewell How are dependencies within this feedstock kept in sync with the aiida-core dependencies?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/sadorf/miniconda3/envs/aiida-1.5.2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
aiida-core                1.5.2              pyhd3deb0d_0    conda-forge
aiida-core.services       1.5.2                hd8ed1ab_0    conda-forge
aldjemy                   0.9.1                      py_2    conda-forge
alembic                   1.5.2              pyhd8ed1ab_0    conda-forge
anyjson                   0.3.3           py37hc8dfbb8_1003    conda-forge
argon2-cffi               20.1.0           py37h5e8e339_2    conda-forge
arrow                     0.17.0           py37h89c1867_1    conda-forge
atk-1.0                   2.36.0               h3371d22_4    conda-forge
babel                     2.9.0              pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bcrypt                    3.2.0            py37h5e8e339_1    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cairo                     1.16.0            h18b612c_1001    conda-forge
certifi                   2020.12.5        py37h89c1867_1    conda-forge
cffi                      1.14.4           py37hc58025e_1    conda-forge
circus                    0.16.1           py37hc8dfbb8_2    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-completion          0.5.2            py37hc8dfbb8_1    conda-forge
click-config-file         0.6.0              pyh9f0ad1d_0    conda-forge
click-spinner             0.1.10             pyh9f0ad1d_0    conda-forge
colour                    0.1.5                      py_0    conda-forge
configobj-dev             2019.9.1                   py_0    conda-forge
cryptography              3.3.1            py37h7f0c10b_1    conda-forge
dbus                      1.13.6               hfdff14a_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
django                    2.2.14           py37hc8dfbb8_0    conda-forge
erlang                    23.2.3               h325e4ec_0    conda-forge
ete3                      3.1.2              pyh9f0ad1d_0    conda-forge
expat                     2.2.9                h9c3ff4c_3    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      2.001                hab24e00_0    conda-forge
font-ttf-source-code-pro  2.030                hab24e00_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            hba837de_1004    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
frozendict                1.2                pyh9f0ad1d_3    conda-forge
furl                      2.1.0                      py_0    conda-forge
future                    0.18.2           py37h89c1867_3    conda-forge
gdk-pixbuf                2.42.2               h0c95a7a_2    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.66.4               hc4f0c31_2    conda-forge
glib-tools                2.66.4               hc4f0c31_2    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
graphviz                  2.42.3               h6939c30_2    conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1
gstreamer                 1.14.0               h28cd5cc_2
gtk2                      2.24.33              hab0c2f8_0    conda-forge
gts                       0.7.6                h64030ff_2    conda-forge
harfbuzz                  2.4.0                hca77d97_0
icu                       58.2              hf484d3e_1000    conda-forge
infinity                  1.4                        py_0    conda-forge
intervals                 0.8.1                      py_0    conda-forge
ipython                   7.19.0           py37hb070fc8_0
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.0           py37h89c1867_2    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
kiwipy                    0.5.5            py37hc8dfbb8_1    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_1    conda-forge
libblas                   3.9.0                7_openblas    conda-forge
libcblas                  3.9.0                7_openblas    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libglib                   2.66.4               h748fe8e_2    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                7_openblas    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     12.3                 h255efa7_3    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libtiff                   4.2.0                hdc55705_0    conda-forge
libtool                   2.4.6             h58526e2_1007    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.1.0                h76fa15c_4    conda-forge
libwebp-base              1.1.0                h36c2ea0_3    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxml2                   2.9.10               hb55368b_3
libxslt                   1.1.34               hc22bd24_0
lxml                      4.6.2            py37h77fd288_1    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
mako                      1.1.4              pyh44b312d_0    conda-forge
markupsafe                1.1.1            py37h5e8e339_3    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
numpy                     1.19.5           py37haa41c4c_1    conda-forge
openssl                   1.1.1i               h7f98852_0    conda-forge
orderedmultidict          1.0.1                      py_0    conda-forge
pango                     1.42.4               h7062337_4    conda-forge
paramiko                  2.7.2              pyh9f0ad1d_0    conda-forge
parso                     0.8.1              pyhd8ed1ab_0    conda-forge
passlib                   1.7.4              pyh9f0ad1d_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pgsu                      0.1.0            py37hc8dfbb8_4    conda-forge
phonenumbers              8.10.14                    py_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pika                      1.1.0              pyh9f0ad1d_1    conda-forge
pip                       21.0               pyhd8ed1ab_1    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
plumpy                    0.15.1             pyh9f0ad1d_0    conda-forge
postgresql                12.3                 hc2f5b80_3    conda-forge
prompt-toolkit            3.0.14             pyha770c72_0    conda-forge
psutil                    5.8.0            py37h5e8e339_1    conda-forge
psycopg2                  2.8.6            py37h7f0c10b_1    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.4              pyhd8ed1ab_0    conda-forge
pynacl                    1.4.0            py37h5e8e339_2    conda-forge
pyqt                      5.9.2            py37hcca6a23_4    conda-forge
python                    3.7.9           hffdb5ce_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-editor             1.0.4                      py_0    conda-forge
python-graphviz           0.16               pyhd3deb0d_1    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.1.2            py37h516909a_1    conda-forge
pyzmq                     21.0.1           py37h499b945_0    conda-forge
qt                        5.9.7                h5867ecd_1
rabbitmq-server           3.8.9                ha770c72_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
reentry                   1.3.1            py37h89c1867_4    conda-forge
scipy                     1.6.0            py37h14a347d_0    conda-forge
setuptools                49.6.0           py37h89c1867_3    conda-forge
shellingham               1.3.2                      py_0    conda-forge
shortuuid                 1.0.1            py37h89c1867_4    conda-forge
simplejson                3.17.2           py37h5e8e339_2    conda-forge
sip                       4.19.8           py37hf484d3e_0
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlalchemy                1.3.22           py37h5e8e339_1    conda-forge
sqlalchemy-utils          0.34.2                     py_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
sqlparse                  0.4.1              pyh9f0ad1d_0    conda-forge
tabulate                  0.8.7              pyh9f0ad1d_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
topika                    0.2.2              pyhd3deb0d_0    conda-forge
tornado                   4.5.3           py37h8f50634_1003    conda-forge
tqdm                      4.56.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
tzcode                    2021a                h7f98852_0    conda-forge
tzlocal                   2.1                pyh9f0ad1d_0    conda-forge
upf_to_json               0.9.2                      py_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wrapt                     1.11.2           py37h8f50634_1    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxpm               3.5.13               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.1.5             h516909a_1003    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zeromq                    4.3.3                h58526e2_3    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.8                ha95c52a_1    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : aiida-1.5.2
    active env location : /home/sadorf/miniconda3/envs/aiida-1.5.2
            shell level : 2
       user config file : /home/sadorf/.condarc
 populated config files : /home/sadorf/.condarc
          conda version : 4.9.0
    conda-build version : not installed
         python version : 3.8.6.final.0
       virtual packages : __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/sadorf/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/sadorf/miniconda3/pkgs
                          /home/sadorf/.conda/pkgs
       envs directories : /home/sadorf/miniconda3/envs
                          /home/sadorf/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.0 requests/2.24.0 CPython/3.8.6 Linux/5.4.0-60-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 1000:1000
             netrc file : /home/sadorf/.netrc
           offline mode : False
```
</details>

**Comment by chrisjsewell** [comment]
> How are dependencies within this feedstock kept in sync with the aiida-core dependencies?

Manually, unfortunately the bot does not update dependencies

**Comment by csadorf** [comment]
Thank you for the quick fix, however, might I suggest that we identify ways to avoid this issue in the future? The aiida-core package has an `environment.yml` file that could be cross-checked, or we could run some very basic tests to ensure that the conda package is not broken? Here it only required a simple `verdi import` command to identify the issue.

**Comment by chrisjsewell** [comment]
Once the upload procedure to anaconda is complete, when you install aiida-core v1.5.2 you should get the build=1 version of the package (let me know if not)

Note, you can ensure that no one can possibly get the build=0 version (see https://github.com/conda-forge/aiida-core-feedstock/issues/32) but I'm not going to personally do that
